version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_TG_BOT_NAME=${NEXT_PUBLIC_TG_BOT_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - TG_BOT_USER=${TG_BOT_USER}
      - TG_BOT_PASS=${TG_BOT_PASS}
    command: sh -c "node server.js"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres:15.1-alpine"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5