import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import Hytkylogo from "../../public/hytkylogo.svg";
import Facebooklogo from "../../public/facebook.svg";
import Instagramlogo from "../../public/instagram.svg";
import Soundcloudlogo from "../../public/soundcloud.svg";
import Miukumauku from "../../public/miukumauku.svg";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>HYTKY</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#000000] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

          <Hytkylogo />

          <div className="justify-center border-2 border-dotted border-orange-600 text-center">
            <h2 className="text-xs tracking-tight text-white">Seuraa meitä</h2>
            <div className="flex flex-row gap-4 pr-1">
              <a
                href="https://www.facebook.com/hytky/"
                target="_blank"
                rel="noreferrer"
              >
                <Facebooklogo width={15} height={15}/>
              </a>
              <a
                href="https://www.instagram.com/hytkyry/"
                target="_blank"
                rel="noreferrer"
              >
                <Instagramlogo width={15} height={15}/>
              </a>
              <a
                href="https://www.soundcloud.com/hytkyry"
                target="_blank"
                rel="noreferrer"
              >
                <Soundcloudlogo width={15} height={15}/>
              </a>
            </div>

          </div>
          <span className="tracking-tight text-white">Kysy sähköpostilla: hytky
            <Miukumauku width={15} height={15} />
              hytky.org
            </span>
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-center text-white hover:bg-white/20"
              href="/eventArchive"
            >
              <h3 className="text-2xl font-bold">Tapahtuma-arkisto →</h3>
              <div className="text-lg">Menneet tapahtumat.</div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-center text-white hover:bg-white/20"
              href="/about"
            >
              <h3 className="text-2xl font-bold italic">HYTKY? →</h3>
              <div className="text-lg">Mikä ihmeen HYTKY?</div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-center text-white hover:bg-white/20"
              href="/rental"
            >
              <h3 className="text-2xl font-bold">Vuokraus →</h3>
              <div className="text-lg">Tietoa laitevuokrauksesta.</div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
