name: npm build

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 19]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: NEXT_PUBLIC_TG_BOT_NAME=github npm ci
      - run: NEXT_PUBLIC_TG_BOT_NAME=github npm run build --if-present